const express = require('express')
const router = express.Router()
const productController = require('../controllers/productController')

router.get('/', productController.getProducts)
router.get('/:id', productController.getProductById)
router.get('/group/:group', productController.getProductsByGroup)
router.get('/user/:id', productController.getProductsByUserId)
router.get('/fav/user/:id', productController.getProductsByFavoredUserId)
router.post('/', productController.createProduct)
//router.put('/:id/answer', productController.addAnswer)
router.put('/:id/fixedquestion/answer', productController.addAnswerForFixedQuestion)
router.put('/:id/uniqquestion/answer', productController.addAnswerForUniqQuestion)
router.put('/:id/question', productController.addUniqQuestion)
//router.put('/:id/highlight', productController.updateHighlight)
router.put('/:id/question/fixed/highlight', productController.addUserToFixedQuestionHighlight)
router.put('/:id/question/uniq/highlight', productController.addUserToUniqQuestionHighlight)
router.put('/:id/question/fixed/unhighlight', productController.removeUserFromFixedQuestionHighlight)
router.put('/:id/question/uniq/unhighlight', productController.removeUserFromUniqQuestionHighlight)
router.put('/:id/favorite', productController.updateFavorite)
router.put('/report', productController.updateReport)

module.exports = router
