const express = require('express')
const router = express.Router()
const productController = require('../controllers/productController')

router.get('/', productController.getProducts)
router.get('/:id', productController.getProductById)
router.get('/group/:group', productController.getProductsByGroup)
router.get('/user/:id', productController.getProductsByUserId)
router.get('/fav/user/:id', productController.getProductsByFavoredUserId)
router.post('/', productController.createProduct)
router.post('/:id/question/fixed/answer', productController.addAnswerToFixedQuestion)
router.post('/:id/question/uniq/answer', productController.addAnswerToUniqQuestion)
router.post('/:id/question', productController.addUniqQuestion)
router.put('/:id/question/fixed/highlight', productController.addUserToFixedQuestionHighlight)
router.put('/:id/question/uniq/highlight', productController.addUserToUniqQuestionHighlight)
router.delete('/:id/question/fixed/:index/highlight/:userId', productController.removeUserFromFixedQuestionHighlight)
router.delete('/:id/question/uniq/:index/highlight/:userId', productController.removeUserFromUniqQuestionHighlight)
router.put('/:id/favor', productController.addUserToFavorite)
router.delete('/:id/favor/:userId', productController.removeUserFromFavorite)
router.put('/report', productController.updateReport)

module.exports = router
