export default [
  { language: 'Arabic', code: 'ar', image: '' },
  { language: 'Chinese', code: 'zh', image: '' },
  { language: 'French', code: 'fr', image: '' },
  { language: 'German', code: 'de', image: '' },
  { language: 'Hindi', code: 'hi', image: '' },
  { language: 'Japanese', code: 'ja', image: '' },
  { language: 'Korean', code: 'ko', image: '' },
  { language: 'Persian', code: 'fa', image: '' },
  { language: 'Portuguese', code: 'pt', image: '' },
  { language: 'Punjabi', code: 'pa', image: '' },
  { language: 'Russian', code: 'ru', image: '' },
  { language: 'Spanish', code: 'es', image: '' },
  { language: 'Ukrainian', code: 'uk', image: '' },
]
